name: dcp_client
description: A Dart client for the Dart Connect Protocol (DCP), an offline-first synchronization protocol.
version: 0.0.2
homepage: https://github.com/jedLahrim/DCP.git

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Storage
  sqflite: ^2.3.0
  path: ^1.9.0
  path_provider: ^2.1.1
  
  # Network
  dio: ^5.3.3
  connectivity_plus: ^5.0.0
  
  # Utils
  uuid: ^4.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.6
